#include <iostream>
#include <string_view>
#include <systemd/sd-journal.h>
#include <unistd.h>
#include <chrono>

// Compile command:
// g++ -std=c++20 sentinel_sshd_tail.cpp -o sentinel_sshd_tail -lsystemd

void extract_and_analyze(sd_journal *journal_context) {
    const void *data;
    size_t length;

    // Retrieve the MESSAGE field from the current journal entry
    int ret = sd_journal_get_data(journal_context, "MESSAGE", &data, &length);
    if (ret < 0) {
        return; // No message field present or read error
    }

    // sd_journal returns the field name AND value (e.g., "MESSAGE=Failed password...")
    std::string_view raw_payload(static_cast<const char*>(data), length);
    
    // Slice off the "MESSAGE=" prefix (8 characters) to isolate the actual log
    std::string_view message = raw_payload.length() > 8 ? raw_payload.substr(8) : raw_payload;

    // Tactical filtering for known SSH failure vectors
    if (message.find("Failed password") != std::string_view::npos ||
        message.find("Invalid user") != std::string_view::npos ||
        message.find("Connection closed") != std::string_view::npos) {
        
        // Extract PRIORITY or other metadata if desired
        std::cout << "\n[ALERT_TRIGGERED] SSHD Failure Detected\n"
                  << "--> Raw Event: " << message << std::endl;
    }
}

int main() {
    sd_journal *journal_context;

    // 1. Open the journal for reading
    int ret = sd_journal_open(&journal_context, SD_JOURNAL_LOCAL_ONLY);
    if (ret < 0) {
        std::cerr << "[CRITICAL] Failed to open journal: " << strerror(-ret) << "\n";
        return 1;
    }

    // 2. Add Match: Only intercept logs generated by sshd.service
    sd_journal_add_match(journal_context, "_SYSTEMD_UNIT=sshd.service", 0);

    // 3. Jump to the end of the journal (the tail)
    sd_journal_seek_tail(journal_context);
    
    // 4. sd_journal_seek_tail points past the end. Step back one to align the read head.
    sd_journal_previous(journal_context);

    std::cout << "[SYSTEM ONLINE] Quantum Flex Sentinel: Tailing sshd_journal... Waiting for connections...\n";

    // 5. The Event Loop
    while (true) {
        // Wait up to 1 second (1,000,000 microseconds) for a new event
        ret = sd_journal_wait(journal_context, 1000000);
        if (ret < 0) {
            std::cerr << "[ERROR] Journal wait failed: " << strerror(-ret) << "\n";
            break;
        }

        // SD_JOURNAL_APPEND indicates new log entries were added
        if (ret == SD_JOURNAL_APPEND) {
            // Iterate through all new entries
            while (sd_journal_next(journal_context) > 0) {
                extract_and_analyze(journal_context);
            }
        }
        // If ret == SD_JOURNAL_NOP, it timed out without new events. Loop continues.
    }

    // 6. Graceful shutdown (Mandatory to prevent descriptor leaks)
    sd_journal_close(journal_context);
    return 0;
}
